/** Design system "Serene Study Guild" — porté depuis l'export Stitch ClassMemo. */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f6fbf0',
        'on-background': '#171d16',
        surface: '#f6fbf0',
        'surface-dim': '#d6dcd1',
        'surface-bright': '#f6fbf0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f5ea',
        'surface-container': '#eaf0e4',
        'surface-container-high': '#e4eadf',
        'surface-container-highest': '#dfe4d9',
        'surface-variant': '#dfe4d9',
        'on-surface': '#171d16',
        'on-surface-variant': '#414944',
        'inverse-surface': '#2c322b',
        'inverse-on-surface': '#edf3e7',
        outline: '#717974',
        'outline-variant': '#c0c8c2',
        primary: '#134231',
        'on-primary': '#ffffff',
        'primary-container': '#2d5a47',
        'on-primary-container': '#9fcfb7',
        'inverse-primary': '#a1d1b9',
        'primary-fixed': '#bcedd4',
        'primary-fixed-dim': '#a1d1b9',
        'on-primary-fixed': '#002115',
        'on-primary-fixed-variant': '#214f3d',
        secondary: '#904d00',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffa453',
        'on-secondary-container': '#713b00',
        'secondary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#ffb77d',
        'on-secondary-fixed': '#2f1500',
        'on-secondary-fixed-variant': '#6e3900',
        tertiary: '#203f4b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#385662',
        'on-tertiary-container': '#abcad9',
        'tertiary-fixed': '#c8e7f7',
        'tertiary-fixed-dim': '#accbda',
        'on-tertiary-fixed': '#001f29',
        'on-tertiary-fixed-variant': '#2d4b57',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        // marqueurs matières
        'subj-psm': '#4f6d7a',
        'subj-gestion': '#477966',
        'subj-iot': '#7e5a8a',
        'subj-ux': '#8a5a2d',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['17px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px' }],
        'body-md': ['15px', { lineHeight: '22px' }],
        'body-sm': ['13px', { lineHeight: '18px' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '600' }],
        caption: ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.75rem',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '2.5rem',
        'safe-bottom-nav': '5.5rem',
      },
      maxWidth: {
        app: '30rem',
      },
      boxShadow: {
        card: '0 2px 8px -2px rgba(28,38,33,0.05), 0 1px 3px -1px rgba(28,38,33,0.03)',
        float: '0 8px 24px -4px rgba(28,38,33,0.10), 0 2px 6px -1px rgba(28,38,33,0.04)',
        'nav-top': '0 -4px 20px rgba(28,38,33,0.06)',
      },
    },
  },
  plugins: [],
};
